// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALwh3I3_dVaEoT2gipBOPZb34Ls8CW5Rs',
    appId: '1:561031704406:web:9b55b9a85c89a373c030f7',
    messagingSenderId: '561031704406',
    projectId: 'assignment-fa9f5',
    authDomain: 'assignment-fa9f5.firebaseapp.com',
    storageBucket: 'assignment-fa9f5.appspot.com',
    measurementId: 'G-M94P50FT0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPaBtGeYUY-or1x-bT_yfoJGwNMiUMxLc',
    appId: '1:561031704406:android:ca1ce82e0a27f2cfc030f7',
    messagingSenderId: '561031704406',
    projectId: 'assignment-fa9f5',
    storageBucket: 'assignment-fa9f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASwFoNjGzaCkAvbeJrbj9bzLe6onx_ubI',
    appId: '1:561031704406:ios:3671bda887c5b959c030f7',
    messagingSenderId: '561031704406',
    projectId: 'assignment-fa9f5',
    storageBucket: 'assignment-fa9f5.appspot.com',
    iosClientId: '561031704406-tl9d399vgdqsham8legqfp61ah9gakp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.assigment',
  );
}
